// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf8gcMSkwleFJk6gXqL5Q9zenXIkMudu0',
    appId: '1:94175353153:web:0bdc926cb0b7ff8482a9c0',
    messagingSenderId: '94175353153',
    projectId: 'shop-app-learning-8f9ce',
    authDomain: 'shop-app-learning-8f9ce.firebaseapp.com',
    databaseURL: 'https://shop-app-learning-8f9ce-default-rtdb.firebaseio.com',
    storageBucket: 'shop-app-learning-8f9ce.appspot.com',
    measurementId: 'G-DKQRVZ0FFG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjC9ODHlxSC5dYiGLJH873DUl1jfsgsY4',
    appId: '1:94175353153:android:be1055d23556b63f82a9c0',
    messagingSenderId: '94175353153',
    projectId: 'shop-app-learning-8f9ce',
    databaseURL: 'https://shop-app-learning-8f9ce-default-rtdb.firebaseio.com',
    storageBucket: 'shop-app-learning-8f9ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj4po-IJHS-To6sL39kRPYte7UzZH3jOM',
    appId: '1:94175353153:ios:794a891f951825d782a9c0',
    messagingSenderId: '94175353153',
    projectId: 'shop-app-learning-8f9ce',
    databaseURL: 'https://shop-app-learning-8f9ce-default-rtdb.firebaseio.com',
    storageBucket: 'shop-app-learning-8f9ce.appspot.com',
    iosBundleId: 'com.example.shopApp.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAj4po-IJHS-To6sL39kRPYte7UzZH3jOM',
    appId: '1:94175353153:ios:cbccc45570e56a8082a9c0',
    messagingSenderId: '94175353153',
    projectId: 'shop-app-learning-8f9ce',
    databaseURL: 'https://shop-app-learning-8f9ce-default-rtdb.firebaseio.com',
    storageBucket: 'shop-app-learning-8f9ce.appspot.com',
    iosBundleId: 'com.example.shopApp',
  );
}
